# Generated by Django 5.2.3 on 2025-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('not_registered', 'Not Registered'), ('admin', 'Admin'), ('patient', 'Patient'), ('therapist', 'Therapist')], default='not_registered', max_length=20),
        ),
    ]
