# Generated by Django 5.2.3 on 2025-07-13 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Iranian mobile number', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
    ]
