# Generated by Django 5.2.3 on 2025-08-06 07:14

import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='user',
            name='is_registration_complete',
            field=models.BooleanField(default=False, verbose_name='Is Registration Complete'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[utils.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[utils.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[utils.validations.validate_iranian_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('admin', 'Admin')], max_length=10, verbose_name='Role'),
        ),
    ]
