# Generated by Django 5.2.3 on 2025-08-09 06:28

import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_remove_user_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_registration_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[utils.validations.validate_iranian_phone_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('admin', 'Admin')], max_length=10),
        ),
    ]
