services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

#  celery_worker:
#    container_name: "otech-celery_worker"
#    command: celery -A config worker --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - redis

volumes:
  postgres_data:
