# Generated by Django 5.2.3 on 2025-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin',
            field=models.CharField(default='self', max_length=100, verbose_name='origin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='reference',
            field=models.URLField(default='http://localhost', verbose_name='reference'),
            preserve_default=False,
        ),
    ]
