# Generated by Django 5.2.3 on 2025-07-13 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='adl_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='assistive_devices_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='balance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='caregiver_diseases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='caregiver_education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cognitive_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='education_level',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(default='tes', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(default='tes', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='environmental_adaptation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='environmental_modifications_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='equipment_used_daily',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='equipment_used_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fatigue_level',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fatigue_management_techniques',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='goal_timeline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='iadl_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='living_environment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='long_term_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobility_aids_used',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='motor_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ms_diagnosis_date',
            field=models.DateField(blank=True, default='2000-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='muscle_strength',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_of_relapses',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='occupational_therapy_received',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_personal_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='physiotherapy_received',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='progress_monitoring',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='psychological_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='recommended_exercises',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='relapse_dates_and_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='session_scheduling',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='short_term_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='speech_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='swallowing_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='therapist_cooperation_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='therapist_team_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='walking_ability',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='years_employed',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='ms_type',
            field=models.CharField(choices=[('RRMS', 'Relapsing Remitting'), ('PPMS', 'Primary Progressive'), ('SPMS', 'Secondary Progressive'), ('CIS', 'Clinically Isolated Syndrome')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('medicine_type', models.CharField(max_length=100)),
                ('medicine_category', models.CharField(max_length=100)),
                ('dosage_amount', models.PositiveIntegerField()),
                ('dosage_unit', models.CharField(max_length=50)),
                ('frequency_per_day', models.PositiveIntegerField()),
                ('frequency_description', models.TextField(blank=True)),
                ('administration_route', models.CharField(max_length=100)),
                ('administration_time', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prescriber_name', models.CharField(max_length=200)),
                ('prescriber_specialty', models.CharField(max_length=100)),
                ('prescription_date', models.DateField()),
                ('prescription_number', models.CharField(max_length=100)),
                ('prescribed_for', models.CharField(max_length=200)),
                ('purpose_description', models.TextField(blank=True)),
                ('effectiveness_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('patient_response', models.CharField(max_length=200)),
                ('response_notes', models.TextField(blank=True)),
                ('has_side_effects', models.BooleanField()),
                ('side_effect_severity', models.CharField(blank=True, max_length=200)),
                ('side_effects', models.TextField(blank=True)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('paused', 'Paused'), ('completed', 'Completed')], max_length=100)),
                ('discontinuation_reason', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProgressMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_improvement', models.TextField()),
                ('performance_loss', models.TextField()),
                ('assessment_date', models.DateField()),
                ('next_assessment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
