# Generated by Django 5.2.3 on 2025-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_number_of_relapses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ms_diagnosis_date',
            field=models.DateField(null=True),
        ),
    ]
