# Generated by Django 5.2.3 on 2025-07-14 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_ms_diagnosis_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='education_level',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Iranian mobile number', regex='^(\\+98)?9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='brand',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='dosage_amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='generic_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='medicine_category',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='medicine_type',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='prescriber_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FFa-zA-Z\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='prescription_number',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Iranian mobile number', regex='^(\\+98)?9\\d{9}$')]),
        ),
    ]
