# Generated by Django 5.2.3 on 2025-08-06 07:14

import datetime
import django.db.models.deletion
import utils.validations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_gender_alter_patient_marital_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='iadl_activities',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='number_of_relapses',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relapse_dates_and_areas',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='administration_route',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='administration_time',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='discontinuation_reason',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='dosage_amount',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='dosage_unit',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='effectiveness_rating',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='frequency_description',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='frequency_per_day',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='generic_name',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='has_side_effects',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='medicine_category',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='medicine_type',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='patient_response',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='prescribed_for',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='prescriber_name',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='prescriber_specialty',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='prescription_date',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='prescription_number',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='purpose_description',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='response_notes',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='side_effect_severity',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='side_effects',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='start_date',
        ),
        migrations.AddField(
            model_name='patientmedicine',
            name='dosage',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientmedicine',
            name='frequency',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200, validators=[utils.validations.validate_address]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adl_activities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assistive_devices_needed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='balance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caregiver_diseases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caregiver_education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cognitive_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_occupation',
            field=models.CharField(blank=True, default='', max_length=100, validators=[utils.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drug_allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='education_level',
            field=models.CharField(max_length=100, validators=[utils.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, validators=[utils.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(max_length=15, validators=[utils.validations.validate_iranian_phone_number]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(max_length=100, validators=[utils.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='environmental_adaptation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='environmental_modifications_needed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='equipment_used_daily',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='equipment_used_work',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_medical_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fatigue_level',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fatigue_management_techniques',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='food_allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='goal_timeline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='living_environment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='long_term_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobility_aids_used',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='motor_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ms_diagnosis_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 6, 7, 14, 9, 694189, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='ms_type',
            field=models.CharField(choices=[('RRMS', 'Relapsing Remitting'), ('PPMS', 'Primary Progressive'), ('SPMS', 'Secondary Progressive'), ('CIS', 'Clinically Isolated Syndrome')], max_length=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='muscle_strength',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(max_length=50, unique=True, validators=[utils.validations.validate_iranian_national_id]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupational_therapy_received',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_personal_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='physiotherapy_received',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='progress_monitoring',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='psychological_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='recommended_exercises',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='session_scheduling',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='short_term_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='speech_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='swallowing_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='therapist_cooperation_level',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='therapist_team_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='walking_ability',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='years_employed',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='name',
            field=models.CharField(max_length=100, validators=[utils.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='patientprogressmonitoring',
            name='performance_improvement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patientprogressmonitoring',
            name='performance_loss',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='PatientRelapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('areas', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
